### ISSUE TITLE
[BUG] exceed 20 minute lifetime of a canister

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/motoko-playground#140]
I don't know if this is supposed to be a hard limit or not, but when calling a very long running method on a canister that overlaps with the time the canister should be uninstalled, it seems like the canister keeps on living forever.

To reproduce:
1. deploy the [REPL](https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=1894631334)
2. from dfx (apparently there's a bug in the agent that doesn't make this work) call `dfx canister --network ic call <canister_id> say '(200 : nat)'`. this should take around 30 minutes to complete
3. see that the canister still exists after more than 30 minutes
4. ???
5. profit

**Comment by chenyan-dfinity** [comment]
20min is a soft limit. You can continue to use the deployed canister unless someone else claimed your canister id after 20min, or the cycles (0.5T) are depleted.
