### ISSUE TITLE
Char interpretation: Playground UI expects input variable Char as Nat32 

### ISSUE THREAD

**Issue by roald-av8** [dfinity/motoko-playground#154]
While trying out a character count function on a _Text_, the Playground UI expects a _nat32_ instead of a _char_ input.
Using ASCII format works but is not convenient of course.

Link to Motoko Playground code: https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=4078707045

**Comment by chenyan-dfinity** [comment]
This is the current spec: https://github.com/dfinity/motoko/blob/master/design/IDL-Motoko.md#type-export. `Char` in Motoko maps to `nat32` in Candid, because we want to support unicode and there is no `char` type in Candid.
