### ISSUE TITLE
Add Support for Uploading gzipped Wasm Modules

### ISSUE THREAD

**Issue by keccak-256** [dfinity/motoko-playground#200]
I am utilizing the Motoko Playground UI to upload and evaluate my compiled Wasm code generated from other CDK. The size of the Wasm file is approximately 8 MB, however, it's restricting that the Wasm size should be under 2 MB. I attempted compression using the gzip method, but unfortunately, the resulting compressed(.gz) binary is not compatible.

**Comment by chenyan-dfinity** [comment]
This is likely not a useful feature. For security reasons, we need to inspect submitted Wasm binary, and this may exceed the instruction limit even with 2MB.

Would deploy to a local replica work for you? Is there a specific feature you need from Playground? We may offer some workaround.

**Comment by keccak-256** [comment]
The canister deployed on the local replica is working fine, but I want to test my canister on a temporary mainnet canister. 
I am trying to deploy using  **dfx deploy  --playground** but I got an error, you can check here I asked: https://forum.dfinity.org/t/error-deploying-canister-on-playground/23030/3

Now I have a question, using CLI -am I able to deploy gzip binary?

**Comment by chenyan-dfinity** [comment]
Nope. Any CLI based on playground would not support gzip. Even if we do, it's under the same instruction limit, and cannot go beyond 2MB. 

Have you tried the faucet wallet? https://internetcomputer.org/docs/current/developer-docs/setup/cycles/cycles-faucet.

**Comment by keccak-256** [comment]
I haven't used the cycle faucet yet, I planned to use the coupon after completing and testing all canisters locally

In the July R&D meeting, dfinity introduced a new feature to upload chunks of wasms through install_code to support larger binaries which they say to be integrated into dfx due to this can we able to deploy on playground?

**Comment by chenyan-dfinity** [comment]
Nope. Playground stays at 2MB due to the instruction limit on inspecting the Wasm. Your best option is to use the cycle faucet.

**Comment by keccak-256** [comment]
Ok, thanks!

**Comment by Mythando** [comment]
I made numerous attempts to get my money back, but in the end I lost $348,000 to a phoney website named mycoinbanking.com. I needed the money to celebrate the holidays, but it was Mr Jeff silbert a recovery specialist, who helped me get my money back from this fraudulent platform. If you require assistance recovering your lost data, I heartily recommend Jeff. His email address is ( Jeffsilbert39 gmail com )
 + 84 94 767 1524 on WhatsApp. Thanks once again Jeff.
