### ISSUE TITLE
request: add a context menu to the deployed canisters to obtain the `dfx canister log`

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko-playground#254]
<img width="194" alt="Screenshot 2024-09-12 at 19 39 40" src="https://github.com/user-attachments/assets/39a8640c-de77-4629-8408-c487901a8660">

Sometimes there is crucial information in the log which the user wants to see. One cannot use the `dfx canister log` command, as there is no controller identity around.

_CAVEAT_: the log may contain garbled unicode characters.

**Comment by chenyan-dfinity** [comment]
May be better to do this in Candid UI, so that it supports canisters outside of playground as well.

**Comment by chenyan-dfinity** [comment]
Done in #260
