### ISSUE TITLE
Unable to run the Motoko playground locally

### ISSUE THREAD

**Issue by milindparikh** [dfinity/motoko-playground#58]
# Main Issue

With the following configuration on ubuntu-20.04
    dfx 0.7.2
    npm 7.18.1
    vessel 0.6.2
    cargo 1.53.0 (4369396ce 2021-04-27)

my  build of wasm-utils is failing at ' dfx deploy --argument '(null)' ' with the following message .

 
"wasm-utils" canister created with canister id: "r7inp-6aaaa-aaaaa-aaabq-cai"
Building canisters...
Executing 'sh -c 'cd wasm-utils && ./build.sh''
    Finished release [optimized] target(s) in 0.05s
./build.sh: line 12: wasm-opt: command not found
Building frontend...
The build step failed for canister 'r7inp-6aaaa-aaaaa-aaabq-cai' with an embedded error: The custom tool failed.

Please help

# Background 

When I first ran 
    dfx deploy --argument '(null)'
    I got 
       error[E0463]: can't find crate for `core`
          |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

I then 
     
     rustup target add wasm32-unknown-unknown

**Comment by chenyan-dfinity** [comment]
You need to download `Binaryen`: https://github.com/WebAssembly/binaryen
If you are using Mac, the easiest is to run `brew install binaryen`
Yes, `rustup target add wasm32-unknown-unknown` is also needed.

I will update the doc.

**Comment by milindparikh** [comment]
thanks!
On ubuntu, doing a `apt install binaryen` works in lieu of brew
