### ISSUE TITLE
func "http_request" in motoko

### ISSUE THREAD

**Issue by LevenSton** [dfinity/motoko-playground#77]
when i query more than 3Mb data from motoko interface, and get a error:
ic0.msg_reply_data_append: application payload size (5735768) cannot be larger than 3145728"

I heard that using func "http_request" in motoko can solve this problem,  how does it work??  use a http request, and can it call the func "http_request" in motoko?  what is the URL?  

example: how to call func "http_request" motoko-playground https://github.com/dfinity/motoko-playground/blob/main/service/pool/Main.mo

**Comment by chenyan-dfinity** [comment]
See https://forum.dfinity.org/t/payload-return-size/5247
